d /opt/ark 0755 ark ark -
d /opt/ark/bus 0750 ark ark -
d /opt/ark/evidence 0750 ark ark -
d /opt/ark/graveyard 0755 root ark -
d /opt/ark/logs 0750 ark ark -
d /var/log/ark 0750 ark ark -
d /etc/ark 0750 root ark -
L /opt/ark/logs - - - - /var/log/ark
